### PR TITLE
refactor(sysctl): Refactor some controller code

### PR DESCRIPTION
**Pull request by matthiasbeyer**
## Description

Some more code refactoring

## Motivation and Context

Not required at all, just found that nice.

## How Has This Been Tested?

It hasn't :laughing: 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [x] Refactor (refactoring production code)
- [ ] Other 

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [ ] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by orhun — APPROVED** [review]
🐻🐻🐻

**Comment by matthiasbeyer** [comment]
A quick bisect told me that the first patch of this series broke this... which I do not understand... do you have some insight?

**Comment by orhun** [comment]
Yup, I just checked `cargo run -- -A` and it lists only the deprecated parameters.

**Comment by matthiasbeyer** [comment]
Should be fixed now, please have another look! :tada:

**Review by orhun — APPROVED** [review]

**Pull request merged**
